<?php

/*
|--------------------------------------------------------------------------
| "Our properties" — TEMPORARY sample set
|--------------------------------------------------------------------------
| Properties will come from Sanity (`estateProperty` type, user decision 2026-09-25). Until then this set feeds the
| page, the navigation badge and the sitemap through `Domain/Properties/Actions/ListProperties`. Photos = the district
| cards' placeholders. Remove as soon as Sanity is wired: nothing here may reach production as is.
*/

return [
    'sample' => [
        ['slug' => 'apartment-saint-germain-des-pres-6th', 'title' => 'Haussmann apartment, Saint-Germain-des-Prés', 'arrondissement' => 6, 'area' => 'Saint-Germain-des-Prés', 'type' => 'apartment', 'transaction' => 'sale', 'price' => 2450000, 'surface' => 128, 'rooms' => 4, 'bedrooms' => 2, 'excerpt' => 'Noble floor, parquet, mouldings and fireplaces, dual aspect over a leafy courtyard and a quiet street.', 'photos' => ['/images/buy/district-1-{w}.webp', '/images/buy/district-2-{w}.webp', '/images/buy/district-3-{w}.webp'], 'photo_alt' => 'Bright Haussmann living room in Saint-Germain-des-Prés', 'advisor' => 1, 'available' => true, 'lat' => 48.8539, 'lng' => 2.3338, 'off_market' => true, 'features' => ['elevator', 'concierge', 'quiet', 'cellar'], 'condition' => 'renovated', 'floor' => 3, 'published_at' => '2026-09-22'],
        ['slug' => 'private-mansion-golden-triangle-8th', 'title' => 'Private mansion, Golden Triangle', 'arrondissement' => 8, 'area' => 'Golden Triangle', 'type' => 'mansion', 'transaction' => 'sale', 'price' => 9800000, 'surface' => 420, 'rooms' => 9, 'bedrooms' => 5, 'excerpt' => 'Enfilade reception rooms, private garden and lift, steps from avenue Montaigne.', 'photos' => ['/images/buy/district-2-{w}.webp', '/images/buy/district-3-{w}.webp', '/images/buy/district-4-{w}.webp'], 'photo_alt' => 'Facade of a private mansion in the Golden Triangle', 'advisor' => 2, 'available' => true, 'lat' => 48.8686, 'lng' => 2.304, 'features' => ['parking', 'terrace', 'cellar', 'view'], 'condition' => 'renovated', 'floor' => 0, 'published_at' => '2026-09-01'],
        ['slug' => 'apartment-champ-de-mars-7th', 'title' => 'Family apartment, Champ-de-Mars', 'arrondissement' => 7, 'area' => 'Champ-de-Mars', 'type' => 'apartment', 'transaction' => 'sale', 'price' => 3150000, 'surface' => 165, 'rooms' => 5, 'bedrooms' => 3, 'excerpt' => 'Open view of the Eiffel Tower from the living room, three bedrooms, absolute quiet.', 'photos' => ['/images/buy/district-3-{w}.webp', '/images/buy/district-4-{w}.webp', '/images/buy/district-1-{w}.webp'], 'photo_alt' => 'Eiffel Tower view from a Champ-de-Mars apartment', 'advisor' => 3, 'available' => false, 'lat' => 48.8556, 'lng' => 2.2986, 'featured' => true, 'features' => ['elevator', 'view', 'balcony', 'concierge', 'top_floor'], 'condition' => 'to_renovate', 'floor' => 5, 'published_at' => '2026-08-15'],
        ['slug' => 'apartment-passy-16th', 'title' => 'Art Deco apartment, Passy', 'arrondissement' => 16, 'area' => 'Passy', 'type' => 'apartment', 'transaction' => 'sale', 'price' => 1890000, 'surface' => 142, 'rooms' => 5, 'bedrooms' => 3, 'excerpt' => 'Serviced building with concierge, wrap-around balcony, close to the international schools.', 'photos' => ['/images/buy/district-4-{w}.webp', '/images/buy/district-1-{w}.webp', '/images/buy/district-2-{w}.webp'], 'photo_alt' => 'Tree-lined street of balconied buildings in Passy', 'advisor' => 1, 'available' => true, 'lat' => 48.8575, 'lng' => 2.279, 'features' => ['elevator', 'balcony', 'concierge', 'cellar'], 'condition' => 'renovated', 'floor' => 4, 'published_at' => '2026-09-25'],
        ['slug' => 'loft-upper-marais-3rd', 'title' => 'Artist loft, Upper Marais', 'arrondissement' => 3, 'area' => 'Upper Marais', 'type' => 'loft', 'transaction' => 'sale', 'price' => 1650000, 'surface' => 118, 'rooms' => 3, 'bedrooms' => 2, 'excerpt' => 'Converted workshop, glass roof, 4.20 m ceilings, cobbled courtyard.', 'photos' => ['/images/buy/district-1-{w}.webp', '/images/buy/district-2-{w}.webp', '/images/buy/district-3-{w}.webp'], 'photo_alt' => 'Glass-roofed loft in the Upper Marais', 'advisor' => 2, 'available' => true, 'lat' => 48.863, 'lng' => 2.3625, 'features' => ['quiet', 'top_floor'], 'condition' => 'renovated', 'floor' => 2, 'published_at' => '2026-09-10'],
        ['slug' => 'apartment-monceau-8th', 'title' => 'Reception apartment, parc Monceau', 'arrondissement' => 8, 'area' => 'Monceau', 'type' => 'apartment', 'transaction' => 'sale', 'price' => 4300000, 'surface' => 210, 'rooms' => 6, 'bedrooms' => 3, 'excerpt' => 'Park view, triple reception, two staff rooms, cellar and parking.', 'photos' => ['/images/buy/district-2-{w}.webp', '/images/buy/district-3-{w}.webp', '/images/buy/district-4-{w}.webp'], 'photo_alt' => 'Reception apartment overlooking parc Monceau', 'advisor' => 3, 'available' => true, 'lat' => 48.8798, 'lng' => 2.309, 'features' => ['elevator', 'view', 'parking', 'cellar', 'concierge'], 'condition' => 'to_renovate', 'floor' => 2, 'published_at' => '2026-07-30'],
        ['slug' => 'rental-furnished-apartment-marais-4th', 'title' => 'Furnished apartment, Marais', 'arrondissement' => 4, 'area' => 'Marais', 'type' => 'apartment', 'transaction' => 'rent', 'price' => 6500, 'surface' => 95, 'rooms' => 3, 'bedrooms' => 2, 'excerpt' => 'Tastefully furnished, beams and parquet, quiet courtyard side, for a mobility or long-term lease.', 'photos' => ['/images/buy/district-3-{w}.webp', '/images/buy/district-4-{w}.webp', '/images/buy/district-1-{w}.webp'], 'photo_alt' => 'Furnished living room with beams in the Marais', 'advisor' => 2, 'available' => true, 'lat' => 48.857, 'lng' => 2.36, 'features' => ['elevator', 'quiet'], 'condition' => 'renovated', 'floor' => 3, 'furnished' => true, 'charges_included' => true, 'published_at' => '2026-09-24'],
        ['slug' => 'rental-terrace-apartment-trocadero-16th', 'title' => 'Apartment with terrace, Trocadéro', 'arrondissement' => 16, 'area' => 'Trocadéro', 'type' => 'apartment', 'transaction' => 'rent', 'price' => 9800, 'surface' => 160, 'rooms' => 5, 'bedrooms' => 3, 'excerpt' => 'South-facing terrace facing the Eiffel Tower, building with concierge, cellar and parking.', 'photos' => ['/images/buy/district-4-{w}.webp', '/images/buy/district-1-{w}.webp', '/images/buy/district-2-{w}.webp'], 'photo_alt' => 'Terrace facing the Eiffel Tower at Trocadéro', 'advisor' => 3, 'available' => true, 'lat' => 48.862, 'lng' => 2.287, 'features' => ['elevator', 'terrace', 'view', 'parking', 'concierge', 'top_floor'], 'condition' => 'new', 'floor' => 6, 'furnished' => false, 'charges_included' => false, 'published_at' => '2026-09-05'],
    ],
];
