<?php

// Pages légales. Mentions légales et politique de confidentialité rédigées le 2026-09-22 (à faire valider juridiquement). Les CGU ont été supprimées le 2026-09-22 (remplacées par le plan du site).
// Les corps acceptent des retours à la ligne (rendu `whitespace-pre-line`) et les jetons :phone / :email / :address (remplacés depuis config/seo.php).
return [
    'privacy' => [
        'title' => 'Politique de confidentialité',
        'description' => 'Découvrez comment Estate in Paris collecte, utilise et protège vos données personnelles, vos droits RGPD et la manière de les exercer auprès de nous.',
        'updated' => 'Dernière mise à jour : :date',
        'sections' => [
            ['heading' => 'Introduction', 'body' => "La présente politique de confidentialité a pour objectif d'informer les utilisateurs du site estate-in-paris.fr de la manière dont leurs données personnelles sont collectées, utilisées et protégées par Estate in Paris.\n\nEstate in Paris s'engage à garantir la sécurité, la confidentialité et la transparence du traitement de vos données, conformément au Règlement général sur la protection des données (RGPD) et à la loi Informatique et Libertés."],
            ['heading' => 'Responsable du traitement', 'body' => "Le responsable du traitement est Estate in Paris, marque commerciale de Veylam OÜ (17548179).\n\nAdresse : :address\nE-mail : :email\nTéléphone : :phone\n\nAucun délégué à la protection des données n'a été désigné ; toute question relative à vos données peut être adressée à :email."],
            ['heading' => 'Données personnelles collectées', 'body' => "Nous collectons uniquement les données strictement nécessaires à la bonne exécution de nos services :\n\n- Formulaire de contact : prénom, nom, adresse e-mail, numéro de téléphone, sujet et message.\n- Demande d'estimation : nom, adresse e-mail, numéro de téléphone, mode de contact souhaité, adresse et caractéristiques du bien (type, surface, étage, pièces, état, atouts, valeur envisagée) et votre message éventuel.\n- Inscription à la newsletter : adresse e-mail.\n- Données de navigation : adresse IP, type d'appareil, navigateur et statistiques de fréquentation anonymisées.\n\nCes données sont fournies volontairement par l'utilisateur via les formulaires du site ou collectées automatiquement lors de la navigation."],
            ['heading' => 'Finalités du traitement', 'body' => "Les données collectées sont utilisées uniquement dans le cadre des services proposés par Estate in Paris :\n\n- Répondre à vos demandes de contact et d'information.\n- Réaliser l'estimation de votre bien et vous accompagner dans votre projet d'achat, de vente ou d'investissement.\n- Vous envoyer notre newsletter hebdomadaire (actualités du marché, analyses, opportunités), sous réserve de votre consentement.\n- Assurer la sécurité du site et prévenir les abus (limitation du nombre d'envois, détection des robots).\n- Mesurer l'audience du site afin d'en améliorer la performance et l'expérience utilisateur."],
            ['heading' => 'Base légale du traitement', 'body' => "Le traitement de vos données repose sur les bases légales suivantes :\n\n- L'exécution de mesures précontractuelles prises à votre demande (réponse à une demande de contact ou d'estimation) et, le cas échéant, l'exécution du contrat.\n- Votre consentement libre, spécifique et éclairé, notamment pour la newsletter et le traitement de votre demande d'estimation.\n- L'intérêt légitime d'Estate in Paris à sécuriser son site, à améliorer ses services et sa relation client.\n- Le respect de nos obligations légales, notamment en matière d'intermédiation immobilière."],
            ['heading' => 'Durée de conservation', 'body' => "Vos données sont conservées uniquement le temps nécessaire aux finalités pour lesquelles elles ont été collectées :\n\n- Demandes de contact et d'estimation : jusqu'à 3 ans après le dernier échange.\n- Données clients : pendant la durée de la relation contractuelle, puis archivées pendant la durée de prescription légale (5 ans).\n- Newsletter : jusqu'à votre désinscription ; votre adresse est ensuite conservée en liste d'opposition.\n- Données liées aux cookies : 13 mois maximum à compter de leur dépôt."],
            ['heading' => 'Destinataires et sous-traitants', 'body' => "Estate in Paris ne vend ni ne loue vos données personnelles. Elles sont traitées par nos conseillers et peuvent être transmises aux prestataires techniques strictement nécessaires au fonctionnement du site :\n\n- Laravel Cloud (Laravel Holdings Inc.), hébergement du site et de sa base de données, serveurs situés à Munich, Allemagne (Union européenne).\n- Resend, envoi des e-mails transactionnels (accusés de réception, e-mail de bienvenue à la newsletter).\n- Google (Google Ireland Ltd.), mesure d'audience via Google Tag Manager et aide à la saisie de l'adresse du bien via Google Places, uniquement lorsque vous utilisez le champ d'adresse.\n- Nos partenaires immobiliers (notaires, diagnostiqueurs, courtiers) impliqués dans votre projet, uniquement avec votre accord.\n- Les autorités administratives ou judiciaires, sur demande conforme à la loi.\n\nCertains de ces prestataires peuvent traiter des données hors de l'Union européenne ; ces transferts sont encadrés par les clauses contractuelles types de la Commission européenne ou un mécanisme équivalent."],
            ['heading' => 'Sécurité et confidentialité', 'body' => "Nous mettons en œuvre les mesures techniques et organisationnelles nécessaires pour garantir la sécurité de vos données : chiffrement des échanges (HTTPS), contrôle des accès, limitation du nombre d'envois de formulaires, sauvegardes sécurisées.\n\nEstate in Paris s'assure que l'ensemble de ses prestataires respecte des standards équivalents de protection des données."],
            ['heading' => 'Vos droits', 'body' => "Conformément au RGPD, vous disposez des droits suivants :\n\n- Droit d'accès à vos données personnelles.\n- Droit de rectification ou d'effacement de vos données.\n- Droit à la limitation ou d'opposition au traitement.\n- Droit à la portabilité de vos données.\n- Droit de retirer votre consentement à tout moment, notamment pour la newsletter (en nous écrivant ou en répondant à l'un de nos e-mails).\n- Droit de définir des directives relatives au sort de vos données après votre décès.\n\nPour exercer ces droits, adressez votre demande à :email. Nous nous engageons à y répondre dans un délai d'un mois.\n\nVous pouvez également déposer une réclamation auprès de la CNIL (www.cnil.fr) si vous estimez que vos droits ne sont pas respectés."],
            ['heading' => 'Cookies et traceurs', 'body' => "Le site utilise des cookies pour assurer son fonctionnement et mesurer son audience :\n\n- Cookies techniques : indispensables au fonctionnement du site (session, sécurité des formulaires). Ils ne nécessitent pas de consentement.\n- Cookies de mesure d'audience : statistiques de fréquentation via Google Tag Manager.\n\nVous pouvez à tout moment refuser ou supprimer les cookies via les paramètres de votre navigateur. Le site n'utilise pas de cookies publicitaires."],
            ['heading' => 'Modifications de la politique', 'body' => "Estate in Paris se réserve le droit de modifier à tout moment la présente politique de confidentialité, notamment pour se conformer à l'évolution de la législation. La date de dernière mise à jour figure en tête de cette page."],
            ['heading' => 'Contact', 'body' => "Pour toute question relative à cette politique ou à la gestion de vos données personnelles, vous pouvez nous contacter :\n\nE-mail : :email\nAdresse postale : Estate in Paris, :address\nTéléphone : :phone"],
        ],
    ],
    'legal' => [
        'title' => 'Mentions légales',
        'description' => 'Mentions légales du site Estate in Paris : identité de l\'éditeur, hébergeur, propriété intellectuelle et contact pour toute question juridique.',
        'updated' => 'Dernière mise à jour : :date',
        'sections' => [
            ['heading' => 'Éditeur du site', 'body' => "Le présent site, accessible à l'adresse estate-in-paris.fr, est édité par Estate in Paris, marque commerciale de Veylam OÜ (17548179).\n\nAdresse : :address\nTéléphone : :phone\nE-mail : :email\nSite web : estate-in-paris.fr\nDirecteur de la publication : M. Leroy, en qualité de responsable de la publication."],
            ['heading' => 'Hébergeur du site', 'body' => "Le site estate-in-paris.fr est hébergé par Laravel Cloud, service édité par Laravel Holdings Inc., 2810 North Church Street, Wilmington, DE 19802, États-Unis.\nLocalisation des serveurs : Munich, Allemagne (Union européenne).\nSite web : cloud.laravel.com"],
            ['heading' => 'Conception et développement', 'body' => "Conception et direction artistique : Estate in Paris.\nDéveloppement web : Estate in Paris.\nDesign et intégration réalisés avec les technologies modernes du web."],
            ['heading' => 'Propriété intellectuelle', 'body' => "L'ensemble du contenu du site (textes, images, graphismes, logo, vidéos, icônes, structure, code source, etc.) est la propriété exclusive d'Estate in Paris, sauf mention contraire.\n\nToute reproduction, représentation, modification, publication, adaptation ou exploitation, totale ou partielle, de ces éléments, quel que soit le moyen ou le procédé utilisé, est interdite sans autorisation écrite préalable.\n\nToute utilisation non autorisée du site ou de son contenu pourra faire l'objet de poursuites conformément aux articles L.335-2 et suivants du Code de la propriété intellectuelle."],
            ['heading' => 'RGPD', 'body' => "Estate in Paris s'engage à ce que la collecte et le traitement de vos données soient conformes au Règlement général sur la protection des données (RGPD) et à la loi Informatique et Libertés.\n\n- Données collectées : formulaire de contact (prénom, nom, e-mail, téléphone, sujet, message) ; formulaire d'estimation (adresse et caractéristiques du bien, nom, e-mail, téléphone) ; inscription à la newsletter (e-mail).\n- Finalités : les données collectées sont utilisées exclusivement pour répondre à vos demandes, assurer la gestion commerciale et vous proposer un accompagnement personnalisé.\n- Conservation : les données sont conservées pour une durée maximale de 3 ans à compter du dernier contact.\n- Droits : conformément au RGPD, vous disposez d'un droit d'accès, de rectification, de suppression ou de limitation du traitement, d'un droit à la portabilité de vos données et d'un droit d'opposition au traitement. Pour exercer vos droits, écrivez à :email."],
            ['heading' => 'Cookies', 'body' => "Le site peut déposer des cookies nécessaires à son fonctionnement et à la mesure d'audience (Google Tag Manager). Vous pouvez paramétrer vos préférences dans les paramètres de votre navigateur.\n\nTypes de cookies utilisés :\n\n- Cookies techniques : indispensables au fonctionnement du site.\n- Cookies analytiques : statistiques de fréquentation anonymes."],
            ['heading' => 'Responsabilité', 'body' => "Estate in Paris s'efforce d'assurer l'exactitude et la mise à jour régulière des informations diffusées sur son site. Elle ne saurait toutefois être tenue responsable d'erreurs ou d'omissions involontaires, d'une indisponibilité temporaire du site, ni de dommages directs ou indirects liés à la consultation ou à l'utilisation du site."],
            ['heading' => 'Liens externes', 'body' => 'Le site peut contenir des liens vers des sites externes. Estate in Paris décline toute responsabilité concernant le contenu ou les pratiques de confidentialité de ces sites tiers.'],
            ['heading' => 'Droit applicable', 'body' => "Les présentes mentions légales sont régies par le droit français. Tout litige relatif à l'utilisation du site sera soumis à la compétence exclusive des tribunaux de Paris."],
        ],
    ],
];
