<?php

/*
|--------------------------------------------------------------------------
| « Nos biens » — jeu d'exemple TEMPORAIRE
|--------------------------------------------------------------------------
| Les biens viendront de Sanity (type `estateProperty`, décision utilisateur 2026-09-25). En attendant, ce jeu alimente
| la page, le badge de navigation et le sitemap via `Domain/Properties/Actions/ListProperties`. Photos = placeholders
| des cartes de quartiers. À retirer dès que Sanity est branché : rien ici ne doit atteindre la prod tel quel.
*/

return [
    'sample' => [
        ['slug' => 'appartement-saint-germain-des-pres-6e', 'title' => 'Appartement haussmannien, Saint-Germain-des-Prés', 'arrondissement' => 6, 'area' => 'Saint-Germain-des-Prés', 'type' => 'apartment', 'transaction' => 'sale', 'price' => 2450000, 'surface' => 128, 'rooms' => 4, 'bedrooms' => 2, 'excerpt' => 'Étage noble, parquet, moulures et cheminées, double exposition sur cour arborée et rue calme.', 'photos' => ['/images/buy/district-1-{w}.webp', '/images/buy/district-2-{w}.webp', '/images/buy/district-3-{w}.webp'], 'photo_alt' => 'Salon haussmannien lumineux à Saint-Germain-des-Prés', 'advisor' => 1, 'available' => true, 'lat' => 48.8539, 'lng' => 2.3338, 'off_market' => true, 'features' => ['elevator', 'concierge', 'quiet', 'cellar'], 'condition' => 'renovated', 'floor' => 3, 'published_at' => '2026-09-22'],
        ['slug' => 'hotel-particulier-triangle-d-or-8e', 'title' => "Hôtel particulier, Triangle d'or", 'arrondissement' => 8, 'area' => "Triangle d'or", 'type' => 'mansion', 'transaction' => 'sale', 'price' => 9800000, 'surface' => 420, 'rooms' => 9, 'bedrooms' => 5, 'excerpt' => 'Réception en enfilade, jardin privatif et ascenseur, à deux pas de l\'avenue Montaigne.', 'photos' => ['/images/buy/district-2-{w}.webp', '/images/buy/district-3-{w}.webp', '/images/buy/district-4-{w}.webp'], 'photo_alt' => "Façade d'un hôtel particulier du Triangle d'or", 'advisor' => 2, 'available' => true, 'lat' => 48.8686, 'lng' => 2.304, 'features' => ['parking', 'terrace', 'cellar', 'view'], 'condition' => 'renovated', 'floor' => 0, 'published_at' => '2026-09-01'],
        ['slug' => 'appartement-champ-de-mars-7e', 'title' => 'Appartement familial, Champ-de-Mars', 'arrondissement' => 7, 'area' => 'Champ-de-Mars', 'type' => 'apartment', 'transaction' => 'sale', 'price' => 3150000, 'surface' => 165, 'rooms' => 5, 'bedrooms' => 3, 'excerpt' => 'Vue dégagée sur la tour Eiffel depuis le séjour, trois chambres, calme absolu.', 'photos' => ['/images/buy/district-3-{w}.webp', '/images/buy/district-4-{w}.webp', '/images/buy/district-1-{w}.webp'], 'photo_alt' => 'Vue sur la tour Eiffel depuis un appartement du Champ-de-Mars', 'advisor' => 3, 'available' => false, 'lat' => 48.8556, 'lng' => 2.2986, 'featured' => true, 'features' => ['elevator', 'view', 'balcony', 'concierge', 'top_floor'], 'condition' => 'to_renovate', 'floor' => 5, 'published_at' => '2026-08-15'],
        ['slug' => 'appartement-passy-16e', 'title' => 'Appartement Art déco, Passy', 'arrondissement' => 16, 'area' => 'Passy', 'type' => 'apartment', 'transaction' => 'sale', 'price' => 1890000, 'surface' => 142, 'rooms' => 5, 'bedrooms' => 3, 'excerpt' => 'Immeuble de standing avec gardien, balcon filant, proche des écoles internationales.', 'photos' => ['/images/buy/district-4-{w}.webp', '/images/buy/district-1-{w}.webp', '/images/buy/district-2-{w}.webp'], 'photo_alt' => 'Rue arborée bordée d\'immeubles à balcons à Passy', 'advisor' => 1, 'available' => true, 'lat' => 48.8575, 'lng' => 2.279, 'features' => ['elevator', 'balcony', 'concierge', 'cellar'], 'condition' => 'renovated', 'floor' => 4, 'published_at' => '2026-09-25'],
        ['slug' => 'loft-haut-marais-3e', 'title' => 'Loft d\'atelier, Haut Marais', 'arrondissement' => 3, 'area' => 'Haut Marais', 'type' => 'loft', 'transaction' => 'sale', 'price' => 1650000, 'surface' => 118, 'rooms' => 3, 'bedrooms' => 2, 'excerpt' => 'Ancien atelier réhabilité, verrière, hauteur sous plafond de 4,20 m, cour pavée.', 'photos' => ['/images/buy/district-1-{w}.webp', '/images/buy/district-2-{w}.webp', '/images/buy/district-3-{w}.webp'], 'photo_alt' => 'Loft à verrière dans le Haut Marais', 'advisor' => 2, 'available' => true, 'lat' => 48.863, 'lng' => 2.3625, 'features' => ['quiet', 'top_floor'], 'condition' => 'renovated', 'floor' => 2, 'published_at' => '2026-09-10'],
        ['slug' => 'appartement-monceau-8e', 'title' => 'Appartement de réception, parc Monceau', 'arrondissement' => 8, 'area' => 'Monceau', 'type' => 'apartment', 'transaction' => 'sale', 'price' => 4300000, 'surface' => 210, 'rooms' => 6, 'bedrooms' => 3, 'excerpt' => 'Vue sur le parc, triple réception, deux chambres de service, cave et parking.', 'photos' => ['/images/buy/district-2-{w}.webp', '/images/buy/district-3-{w}.webp', '/images/buy/district-4-{w}.webp'], 'photo_alt' => 'Appartement de réception avec vue sur le parc Monceau', 'advisor' => 3, 'available' => true, 'lat' => 48.8798, 'lng' => 2.309, 'features' => ['elevator', 'view', 'parking', 'cellar', 'concierge'], 'condition' => 'to_renovate', 'floor' => 2, 'published_at' => '2026-07-30'],
        ['slug' => 'location-appartement-meuble-marais-4e', 'title' => 'Appartement meublé, Marais', 'arrondissement' => 4, 'area' => 'Marais', 'type' => 'apartment', 'transaction' => 'rent', 'price' => 6500, 'surface' => 95, 'rooms' => 3, 'bedrooms' => 2, 'excerpt' => 'Meublé avec goût, poutres et parquet, au calme sur cour, disponible pour un bail mobilité ou longue durée.', 'photos' => ['/images/buy/district-3-{w}.webp', '/images/buy/district-4-{w}.webp', '/images/buy/district-1-{w}.webp'], 'photo_alt' => 'Séjour meublé avec poutres dans le Marais', 'advisor' => 2, 'available' => true, 'lat' => 48.857, 'lng' => 2.36, 'features' => ['elevator', 'quiet'], 'condition' => 'renovated', 'floor' => 3, 'furnished' => true, 'charges_included' => true, 'published_at' => '2026-09-24'],
        ['slug' => 'location-appartement-terrasse-trocadero-16e', 'title' => 'Appartement avec terrasse, Trocadéro', 'arrondissement' => 16, 'area' => 'Trocadéro', 'type' => 'apartment', 'transaction' => 'rent', 'price' => 9800, 'surface' => 160, 'rooms' => 5, 'bedrooms' => 3, 'excerpt' => 'Terrasse plein sud face à la tour Eiffel, immeuble avec gardien, cave et parking.', 'photos' => ['/images/buy/district-4-{w}.webp', '/images/buy/district-1-{w}.webp', '/images/buy/district-2-{w}.webp'], 'photo_alt' => 'Terrasse avec vue sur la tour Eiffel au Trocadéro', 'advisor' => 3, 'available' => true, 'lat' => 48.862, 'lng' => 2.287, 'features' => ['elevator', 'terrace', 'view', 'parking', 'concierge', 'top_floor'], 'condition' => 'new', 'floor' => 6, 'furnished' => false, 'charges_included' => false, 'published_at' => '2026-09-05'],
    ],
];
